# Generated by Django 4.2.5 on 2023-09-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
