# Generated by Django 4.2.5 on 2023-10-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Int_field',
            field=models.IntegerField(default=12),
        ),
    ]
