# Generated by Django 4.2.5 on 2023-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_wallet', models.PositiveIntegerField(default=0)),
                ('business_wallet', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
