# Generated by Django 4.2.5 on 2023-11-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
