# Generated by Django 4.2.5 on 2023-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_wallets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
